import { ArrowRight, MapPin, CalendarDays, Zap, Trophy, Gamepad2, Brain, Users, Target, Heart, Layers, Plug, Rocket, Ticket } from "lucide-react";
import { EVENT_TEAM } from "@/lib/site";
import BrandImg from "./brand-img";
import BookingLink from "./booking-link";
import InterestPicker from "./interest-picker";
import "./summit.css";
const assets = "/assets/promofy/";
function Book({ placement, children = "Book a Meeting" }: { placement: string; children?: React.ReactNode }) {
  return <BookingLink href={EVENT_TEAM[2].bookingHref} placement={placement} className="s-button">{children}<ArrowRight size={17}/></BookingLink>;
}
const features = [
  { title: "Acquisition", Icon: Users, copy: "Turn first impressions into participation with interactive campaigns." },
  { title: "Engagement", Icon: Trophy, copy: "Missions, leaderboards and challenges that give players a reason to play." },
  { title: "Retention", Icon: Heart, copy: "Build daily habits with streaks, rewards and lifecycle journeys." },
  { title: "Intelligence", Icon: Brain, copy: "AI-assisted creation, segmentation and campaign optimisation." },
  { title: "Sports", Icon: Target, copy: "Predictions, pick’em games and live moments for every fan." },
  { title: "Scale", Icon: Layers, copy: "One engagement platform for multiple brands and markets." },
];
function Proof() { return <div className="s-proof"><div><BrandImg src={assets + "Ice.png"} alt="ICE" width={70}/><span>2026<br/>Startup Winner</span></div><div><BrandImg src={assets + "Starties-Thrasher-Transparent-1.png"} alt="Starties" width={90} fallbackText="STARTIES"/><span>Launch of the Year</span></div></div>; }
export function EventLandingPage() {
  return <div className="summit-page"><a className="skip-link" href="#main">Skip to content</a>
    <header className="s-header"><div className="s-shell"><a href="#top" aria-label="Promofy home"><BrandImg src={assets + "promofy-logo.svg"} alt="Promofy" width={142} height={40} loading="eager"/></a><nav aria-label="Main navigation"><a href="#experience">SBC Lisbon</a><a href="#showcase">Showcase</a><a href="#why-promofy">Why Promofy</a><a href="#meet-us">Meet the Team</a><a href="/rsvp/">RSVP</a></nav><Book placement="header"/></div></header>
    <main id="main">
      <section className="s-hero" id="top"><div className="s-shell"><div className="s-hero-copy"><p className="s-eyebrow">SBC SUMMIT LISBON · 29 SEPT – 1 OCT 2026 · STARTUP HUB S18</p><h1>Turn<br/>Engagement <em>ON.</em></h1><h2>Meet Promofy in Lisbon.</h2><p>Acquisition. Gamification. Retention. Loyalty.<br/>One engagement ecosystem for operators, platforms and game studios.</p><div className="s-actions"><Book placement="hero"/><a className="s-button s-outline" href="#showcase">See Our Product Showcase</a></div><div className="s-location"><span><MapPin size={17}/> Startup Hub · S18</span><a href="#showcase"><CalendarDays size={17}/> Product Innovation Stage</a><a href="/rsvp/"><Ticket size={17}/> RSVP for S18</a></div></div><div className="s-hero-art s-hero-art--abstract" aria-hidden="true"/><Proof/></div></section>
      <section className="s-light s-experience" id="experience"><div className="s-shell"><p className="s-eyebrow">THREE WAYS TO EXPERIENCE PROMOFY</p><div className="s-section-heading"><h2>Don’t just hear about Promofy.<br/>Experience it in Lisbon.</h2><p>One visit. Three ways to see what Promofy can do for your players and your business.</p></div><div className="s-experience-grid">{[
        { word: "MEET", title: "30 minutes.\nYour growth challenge.", copy: "Bring your engagement challenge. Leave with a practical next step for your business.", image: "promofy-signal-system.webp", cta: <Book placement="experience_meet"/> },
        { word: "VISIT", title: "See Promofy live\nat S18.", copy: "Explore Spark, Sports F2P, Gamification, AI and Jackpots, live at the Startup Hub.", image: "promofy-sbc-hero.webp", cta: <a href="#visit" className="s-button">Find Us at S18 <ArrowRight size={17}/></a> },
        { word: "WATCH", title: "The Promofy\nProduct Showcase.", copy: "Follow the player journey from first interaction to lasting loyalty, live on stage.", image: "Image-container-2.avif", cta: <a href="#showcase" className="s-button">Explore the Showcase <ArrowRight size={17}/></a> },
      ].map((x,i)=><article className="s-experience-card" key={x.word}><BrandImg className="s-card-art" src={assets+x.image} alt=""/><div className="s-card-label"><span>0{i+1}</span><strong>{x.word}</strong></div><div className="s-card-copy"><h3>{x.title}</h3><p>{x.copy}</p>{x.cta}</div></article>)}</div></div></section>
      <section className="s-showcase" id="showcase"><div className="s-shell s-showcase-grid"><div><p className="s-eyebrow">PRODUCT INNOVATION STAGE</p><h2>From Player Moment<br/>to Revenue Moment.</h2><h3 className="s-pink">The Promofy Showcase</h3><p>Follow the engagement journey live — from the first interaction to repeat participation, retention and monetisation.</p><div className="s-journey">{[Users, Gamepad2, Heart, Target].map((Icon,i)=><div key={i}><Icon/><span>{["ACQUIRE", "ENGAGE", "RETAIN", "MONETISE"][i]}</span></div>)}</div><div className="s-actions"><a href="#visit" className="s-button">Plan Your Visit <ArrowRight size={17}/></a><Book placement="showcase">Meet the Team</Book></div></div><div><div className="s-stage-info"><CalendarDays/><div><strong>SBC SUMMIT LISBON 2026</strong><p>Product Innovation Stage<br/>Showcase date and time to be confirmed</p></div></div><div className="s-products">{[{name:"Spark",Icon:Zap,copy:"Turn anonymous traffic into active participants."},{name:"Sports F2P",Icon:Trophy,copy:"Activate fans around live sport and matchdays."},{name:"Gamification",Icon:Gamepad2,copy:"Build missions, journeys and loyalty loops."},{name:"AI",Icon:Brain,copy:"Create campaigns and personalise engagement."}].map(({name,Icon,copy})=><a href="#why-promofy" key={name}><Icon/><h4>{name}</h4><p>{copy}</p></a>)}</div></div></div></section>
      <section className="s-light s-features" id="why-promofy"><div className="s-shell"><div className="s-section-heading"><div><p className="s-eyebrow">THE ENGAGEMENT ECOSYSTEM</p><h2>More ways to turn growth ON.</h2></div><p>Connect every stage of the player journey.<br/>Start where your business needs it most.</p></div><div className="s-feature-grid">{features.map(({title,Icon,copy})=><article key={title}><h3>{title}</h3><div className="s-on">ON <span aria-hidden="true"/></div><Icon/><p>{copy}</p></article>)}</div><a href="https://promofy.ai/" className="s-button s-centered">Show Me the Platform <ArrowRight size={17}/></a></div></section>
      <section className="s-light s-team" id="meet-us"><div className="s-shell"><div className="s-team-grid"><div className="s-team-intro"><p className="s-eyebrow">YOUR TEAM IN LISBON</p><h2>Meet the people<br/>building Promofy.</h2><p>Strategy. Product. Commercial.<br/>A team that understands your world.</p><a href="#request-meeting" className="s-text-link">Find Your Conversation <ArrowRight size={17}/></a></div>{EVENT_TEAM.map(member=><article className="s-person" key={member.id}><div className="s-portrait" aria-label={member.name}><span>{member.initials}</span><small>MEET US IN LISBON ↗</small></div><div className="s-person-copy"><h3>{member.name}</h3><strong>{member.role}</strong><p>{member.focus}</p><div><BookingLink href={member.bookingHref} placement={`team_${member.id}`}>Meet {member.name.split(" ")[0]} →</BookingLink><a href={member.linkedinHref} target="_blank" rel="noopener noreferrer" aria-label={`${member.name} on LinkedIn`}><span className="s-linkedin" aria-hidden="true">in</span></a></div></div></article>)}</div><div className="s-team-route"><CalendarDays/><div><h3>Not sure who to meet?</h3><p>Tell us what you’re working on. We’ll point you to the right person.</p></div><a href="#request-meeting" className="s-text-link">Help Me Choose <ArrowRight size={17}/></a></div></div></section>
      <InterestPicker/>
      <section className="s-light s-integration"><div className="s-shell"><div className="s-stack" aria-hidden="true">{["Your platform", "Your CRM", "Promofy", "Spark"].map(x=><span key={x}><Layers/>{x}</span>)}</div><div><p className="s-eyebrow">INTEGRATION</p><h2>Fits your stack.<br/>Not the other way around.</h2><p>API-first. CRM-connected. Flexible by design.<br/>Build on the technology you already use.</p><div className="s-integration-steps">{[{Icon:Rocket,title:"Start Small",copy:"Launch a focused use case first."},{Icon:Plug,title:"Integrate Once",copy:"Expand capabilities over time."},{Icon:Zap,title:"Operate Fast",copy:"Put campaign creation in your team’s hands."}].map(({Icon,title,copy})=><div key={title}><Icon/><span><strong>{title}</strong><small>{copy}</small></span></div>)}</div></div><Book placement="integration">Discuss My Integration</Book></div></section>
      <section className="s-final" id="visit"><div className="s-shell"><p className="s-eyebrow">SBC SUMMIT LISBON 2026</p><h2>Lisbon.<br/>Promofy is <em>ON.</em></h2><p>29 September – 1 October 2026<br/>Feira Internacional de Lisboa · Startup Hub · S18<br/>Product Innovation Stage · Promofy Showcase</p><div className="s-actions"><Book placement="final">Book My Meeting</Book><a className="s-button s-outline" href="/rsvp/">RSVP for S18 <ArrowRight size={17}/></a><a className="s-button s-outline" href="#showcase">Explore the Showcase <ArrowRight size={17}/></a></div><span className="s-handwritten">Let’s turn<br/>engagement ON<br/>together.</span></div></section>
    </main><footer className="s-footer"><div className="s-shell"><BrandImg src={assets+"promofy-logo.svg"} alt="Promofy" width={116}/><span>Turn player moments into more.</span><nav aria-label="Footer"><a href="https://promofy.ai/">Platform</a><a href="#meet-us">Team</a><a href="#request-meeting">Contact</a><a href="https://www.linkedin.com/company/promofyai/" aria-label="Promofy on LinkedIn"><span className="s-linkedin" aria-hidden="true">in</span></a></nav><small>© 2026 Promofy</small></div></footer>
  </div>;
}


